defaults:
  - _self_
  - augmentations: base.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "adabn"
method: "adabn"
backbone:
  name: "resnet18"
  kwargs:
    # weights: "IMAGENET1K_V2"
    pretrained: True
data:
  dataset: cloc
  train_path: "~/github/solo-learn/datasets/"
  num_workers: 12
online:
  sup_buffer_size: 40000
  delay: 0
  batch_repeat: 1
  imbalanced:
    enabled: False
    supervised: 1
    unsupervised: 9
category: "TTA"
optimizer:
  name: "sgd"
  batch_size: 128
  lr: 0.005
  weight_decay: 1e-5
  momentum: 0.9
  classifier_lr: 0.005
# optimizer:
#   name: "sgd"
#   batch_size: 128
#   lr: 0.005
#   weight_decay: 1e-5
#   momentum: 0.9
#   classifier_lr: 0.005
# optimizer:
#   name: "lars"
#   batch_size: 128
#   lr: 0.3
#   classifier_lr: 0.1
#   weight_decay: 1e-4
#   kwargs:
#     clip_lr: True
#     eta: 0.02
#     exclude_bias_n_norm: True
# optimizer:
#   name: "adam"
#   batch_size: 64
#   lr: 0.001
#   weight_decay: 1e-5
#   momentum: 0.9
#   classifier_lr: 0.001
scheduler:
  # name: "warmup_cosine"
  name: "none"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1000
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16



log_every_n_steps: 20
# overfit_batches: 10
debug_augmentations: True
