defaults:
  - _self_
  - augmentations: ressl.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "ressl"
method: "ressl"
backbone:
  name: "resnet18"
  kwargs:
    # weights: "IMAGENET1K_V2"
    pretrained: True
method_kwargs:
  proj_output_dim: 256
  proj_hidden_dim: 4096
  base_tau_momentum: 0.99
  final_tau_momentum: 1.0
  momentum_classifier:
  temperature_q: 0.1
  temperature_k: 0.04
  scale_loss: 0.3
momentum:
  base_tau: 0.99
  final_tau: 1.0
data:
  dataset: cloc
  train_path: "~/github/solo-learn/datasets/"
  num_workers: 12
category: "SSL"
online:
  sup_buffer_size: 40000
  delay: 0
  num_supervised: 1
  num_unsupervised: 1
optimizer:
  name: "sgd"
  batch_size: 128
  lr: 0.005
  weight_decay: 1e-5
  momentum: 0.9
  classifier_lr: 0.005
scheduler:
  # name: "warmup_cosine"
  name: "none"
checkpoint:
  enabled: True
  dir: "trained_models"
  train_time_interval: 3500 # seconds
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 1
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
precision: 16



log_every_n_steps: 20
# overfit_batches: 10
debug_augmentations: True