defaults:
  - _self_
  - augmentations: base.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "sar"
method: "sar"
backbone:
  name: "resnet18"
  kwargs:
    # weights: "IMAGENET1K_V2"
    pretrained: True
method_kwargs:
  scale_loss1: 1.0
  scale_loss2: 0.1
  scale_margin: 0.4
  recovery: 0.2
  warmup: 10000
  tta_lr: 1e-4
data:
  dataset: cloc
  train_path: "~/github/solo-learn/datasets/"
  num_workers: 14
  prefetch_factor: 50
category: "TTA"
online:
  sup_buffer_size: 40000
  delay: 0
  num_supervised: 1
  num_unsupervised: 1
  supervised_projection_head:
    enabled: False
    output_dim: 256
    hidden_dim: 2048
    num_layers: 2
  supervised_param_names: ["backbone", "classifier"]
optimizer:
  name: "sgd"
  batch_size: 128
  lr: 0.005
  weight_decay: 1e-5
  momentum: 0.9
  classifier_lr: 0.005
scheduler:
  # name: "warmup_cosine"
  name: "none"
checkpoint:
  enabled: True
  dir: "trained_models"
  train_time_interval: 3500 # seconds
  # not using 3600 because the scheduler 
  # usually shuts down the job at the full hour
auto_resume:
  enabled: False
  max_hours: 1000
# overwrite PL stuff
max_epochs: 1
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
precision: 16

log_every_n_steps: 20
log_histogram_every_n_steps: 100
debug_augmentations: True
ckpt_path: ""